# Generated by Django 6.0.5 on 2026-05-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="hod",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"user_type": "1"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_course",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
