# Generated by Django 6.0.5 on 2026-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_course_hod"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("hod", "Head of Department"),
                    ("coordinator", "Coordinator"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="role_detail",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
