# Generated by Django 6.0.5 on 2026-05-28 13:24

from django.db import migrations, models


def normalize_existing_roles(apps, schema_editor):
    Staff = apps.get_model('main_app', 'Staff')
    role_map = {
        'staff': 'Teacher',
        'hod': 'HOD',
        'coordinator': 'Coordinator',
    }
    for staff in Staff.objects.all().only('id', 'role'):
        current = (staff.role or '').strip().lower()
        if current in role_map:
            staff.role = role_map[current]
            staff.save(update_fields=['role'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_backfill_missing_user_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(default="Teacher", max_length=120),
        ),
        migrations.RunPython(normalize_existing_roles, reverse_noop),
    ]
