# Generated by Django 5.2.14 on 2026-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_assessmentmark_assignment_bookloan_kaajrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
